In [261]:
# this is the original data frame
poke_df <- read.csv("C:/Users/kgtrm/Documents/R projects data/archive pokemon better/Pokemon Database.csv")
head(poke_df)
str(poke_df)

  ï..Pokemon.Id Pokedex.Number Pokemon.Name Classification
1 1             1              "Bulbasaur"  "Seed Pokemon"
2 2             2              "Ivysaur"    "Seed Pokemon"
3 3             3              "Venusaur"   "Seed Pokemon"
4 4             3              "Venusaur"   "Seed Pokemon"
5 5             4              "Charmander" "Lizard Pokemon"
6 6             5              "Charmeleon" "Flame Pokemon"
  Alternate.Form.Name Original.Pokemon.ID Legendary.Type Pokemon.Height
1 NULL                NULL                NULL           0.7
2 NULL                NULL                NULL           1.0
3 NULL                NULL                NULL           2.0
4 "Mega"              3                   NULL           2.4
5 NULL                NULL                NULL           0.6
6 NULL                NULL                NULL           1.1
  Pokemon.Weight Primary.Type ... EV.Yield.Total Catch.Rate Experience.Growth
1   6.9          "Grass"      ... 1              45         "Medium Slow"
2  13.0          "Grass"      ... 2              45         "Medium Slow"
3 100.0          "Grass"      ... 3              45         "Medium Slow"
4 155.5          "Grass"      ... 3              45         "Medium Slow"
5   8.5          "Fire"       ... 1              45         "Medium Slow"
6  19.0          "Fire"       ... 2              45         "Medium Slow"
  Experience.Growth.Total Experience.Yield Primary.Egg.Group
1 1059860                  64              "Monster"
2 1059860                 142              "Monster"
3 1059860                 236              "Monster"
4 1059860                 281              "Monster"
5 1059860                  62              "Monster"
6 1059860                 142              "Monster"
  Secondary.Egg.Group Egg.Cycle.Count Pre.Evolution.Pokemon.Id
1 "Grass"             20              NULL
2 "Grass"             20              1
3 "Grass"             20              2
4 "Grass"             20              NULL
5 "Dragon"            20              NULL
6 "Dragon"            20              5
  Evolution.Details
1 NULL
2 "Level 16"
3 "Level 32"
4 NULL
5 NULL
6 "Level 16"

'data.frame':	1076 obs. of  47 variables:
 $ ï..Pokemon.Id                    : int  1 2 3 4 5 6 7 8 9 10 ...
 $ Pokedex.Number                   : int  1 2 3 3 4 5 6 6 6 7 ...
 $ Pokemon.Name                     : chr  "\"Bulbasaur\"" "\"Ivysaur\"" "\"Venusaur\"" "\"Venusaur\"" ...
 $ Classification                   : chr  "\"Seed Pokemon\"" "\"Seed Pokemon\"" "\"Seed Pokemon\"" "\"Seed Pokemon\"" ...
 $ Alternate.Form.Name              : chr  "NULL" "NULL" "NULL" "\"Mega\"" ...
 $ Original.Pokemon.ID              : chr  "NULL" "NULL" "NULL" "3" ...
 $ Legendary.Type                   : chr  "NULL" "NULL" "NULL" "NULL" ...
 $ Pokemon.Height                   : num  0.7 1 2 2.4 0.6 1.1 1.7 1.7 1.7 0.5 ...
 $ Pokemon.Weight                   : num  6.9 13 100 155.5 8.5 ...
 $ Primary.Type                     : chr  "\"Grass\"" "\"Grass\"" "\"Grass\"" "\"Grass\"" ...
 $ Secondary.Type                   : chr  "\"Poison\"" "\"Poison\"" "\"Poison\"" "\"Poison\"" ...
 $ Primary.Ability                  : chr  "\"Overgrow\"" "\"Overgrow\"" "\"Overgrow\"" "\"Thick Fat\"" ...
 $ Primary.Ability.Description      : chr  "\"Powers up Grass-type moves when the PokÃ©mon's HP is low.\"" "\"Powers up Grass-type moves when the PokÃ©mon's HP is low.\"" "\"Powers up Grass-type moves when the PokÃ©mon's HP is low.\"" "\"The PokÃ©mon is protected by a layer of thick fat, which halves the damage taken from Fire- and Ice-type moves. \"" ...
 $ Secondary.Ability                : chr  "NULL" "NULL" "NULL" "NULL" ...
 $ Secondary.Ability.Description    : chr  "NULL" "NULL" "NULL" "NULL" ...
 $ Hidden.Ability                   : chr  "\"Chlorophyll\"" "\"Chlorophyll\"" "\"Chlorophyll\"" "NULL" ...
 $ Hidden.Ability.Description       : chr  "\"Boosts the PokÃ©mon's Speed stat in harsh sunlight. \"" "\"Boosts the PokÃ©mon's Speed stat in harsh sunlight. \"" "\"Boosts the PokÃ©mon's Speed stat in harsh sunlight. \"" "NULL" ...
 $ Special.Event.Ability            : chr  "NULL" "NULL" "NULL" "NULL" ...
 $ Special.Event.Ability.Description: chr  "NULL" "NULL" "NULL" "NULL" ...
 $ Male.Ratio                       : num  87.5 87.5 87.5 87.5 87.5 87.5 87.5 87.5 87.5 87.5 ...
 $ Female.Ratio                     : num  12.5 12.5 12.5 12.5 12.5 12.5 12.5 12.5 12.5 12.5 ...
 $ Base.Happiness                   : int  70 70 70 70 70 70 70 70 70 70 ...
 $ Game.s..of.Origin                : chr  "\"Red\"" "\"Red\"" "\"Red\"" "\"X\"" ...
 $ Region.of.Origin                 : chr  "\"Kanto\"" "\"Kanto\"" "\"Kanto\"" "\"Kalos\"" ...
 $ Health.Stat                      : int  45 60 80 80 39 58 78 78 78 44 ...
 $ Attack.Stat                      : int  49 62 82 100 52 64 84 130 104 48 ...
 $ Defense.Stat                     : int  49 63 83 123 43 58 78 111 78 65 ...
 $ Special.Attack.Stat              : int  65 80 100 122 60 80 109 130 159 50 ...
 $ Special.Defense.Stat             : int  65 80 100 120 50 65 85 85 115 64 ...
 $ Speed.Stat                       : int  45 60 80 80 65 80 100 100 100 43 ...
 $ Base.Stat.Total                  : int  318 405 525 625 309 405 534 634 634 314 ...
 $ Health.EV                        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Attack.EV                        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Defense.EV                       : int  0 0 0 0 0 0 0 0 0 1 ...
 $ Special.Attack.EV                : int  1 1 2 2 0 1 3 3 3 0 ...
 $ Special.Defense.EV               : int  0 1 1 1 0 0 0 0 0 0 ...
 $ Speed.EV                         : int  0 0 0 0 1 1 0 0 0 0 ...
 $ EV.Yield.Total                   : int  1 2 3 3 1 2 3 3 3 1 ...
 $ Catch.Rate                       : int  45 45 45 45 45 45 45 45 45 45 ...
 $ Experience.Growth                : chr  "\"Medium Slow\"" "\"Medium Slow\"" "\"Medium Slow\"" "\"Medium Slow\"" ...
 $ Experience.Growth.Total          : int  1059860 1059860 1059860 1059860 1059860 1059860 1059860 1059860 1059860 1059860 ...
 $ Experience.Yield                 : int  64 142 236 281 62 142 240 285 285 63 ...
 $ Primary.Egg.Group                : chr  "\"Monster\"" "\"Monster\"" "\"Monster\"" "\"Monster\"" ...
 $ Secondary.Egg.Group              : chr  "\"Grass\"" "\"Grass\"" "\"Grass\"" "\"Grass\"" ...
 $ Egg.Cycle.Count                  : int  20 20 20 20 20 20 20 20 20 20 ...
 $ Pre.Evolution.Pokemon.Id         : chr  "NULL" "1" "2" "NULL" ...
 $ Evolution.Details                : chr  "NULL" "\"Level 16\"" "\"Level 32\"" "NULL" ...

In [1]:
library(tidyr)
library(dplyr)

Attaching package: 'dplyr'


The following objects are masked from 'package:stats':

    filter, lag


The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

In [135]:
# this is the raw file for fully evolved pokemon. I am going to extract a list so I can add another attribute to the above table
evolved_raw <- read.delim("C:/Users/kgtrm/Documents/VSC Code/R stuff/Pokemon evolved raw data.txt")
head(evolved_raw)

evolved_split <- evolved_raw %>%
    separate(X...small.Average..small., into = c("temp", "num", "Name"), sep = "\\|") %>%
    select(Name)
head(evolved_split)
str(evolved_split)

  X...small.Average..small.
1 {{lop/base|003|Venusaur|80|82|83|100|100|80}}
2 {{lop/base|003M|Venusaur|80|100|123|122|120|80|Mega Venusaur}}
3 {{lop/base|006|Charizard|78|84|78|109|85|100}}
4 {{lop/base|006MX|Charizard|78|130|111|130|85|100|Mega Charizard X}}
5 {{lop/base|006MY|Charizard|78|104|78|159|115|100|Mega Charizard Y}}
6 {{lop/base|009|Blastoise|79|83|100|85|105|78}}

Warning message:
"Expected 3 pieces. Additional pieces discarded in 606 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, ...]."

  Name
1 Venusaur
2 Venusaur
3 Charizard
4 Charizard
5 Charizard
6 Blastoise

'data.frame':	606 obs. of  1 variable:
 $ Name: chr  "Venusaur" "Venusaur" "Charizard" "Charizard" ...

In [162]:
# now I need this as a list

evolved_list = c()
for (i in 1:nrow(evolved_split)) {
    evolved_list <- append(evolved_list, evolved_split[i,])
}

evolved_list <- unique(evolved_list)
head(evolved_list)

[1] "Venusaur"   "Charizard"  "Blastoise"  "Butterfree" "Beedrill"
[6] "Pidgeot"

In [262]:
# now let's add a column to denote whether a pokemon is fully evolved or not
# note that the Pokemon.Name contains strings with "" included in the string. so we need to remove those
# let's go ahead and do that for all columns where it is needed
poke_df$Pokemon.Name <- gsub("\"", "", poke_df$Pokemon.Name)
poke_df$Classification <- gsub("\"", "", poke_df$Classification)
poke_df$Alternate.Form.Name <- gsub("\"", "", poke_df$Alternate.Form.Name)
poke_df$Experience.Growth <- gsub("\"", "", poke_df$Experience.Growth)
poke_df$Primary.Egg.Group <- gsub("\"", "", poke_df$Primary.Egg.Group)
poke_df$Secondary.Egg.Group <- gsub("\"", "", poke_df$Secondary.Egg.Group)
poke_df$Evolution.Details <- gsub("\"", "", poke_df$Evolution.Details)
poke_df$Primary.Type <- gsub("\"", "", poke_df$Primary.Type)
poke_df$Secondary.Type <- gsub("\"", "", poke_df$Secondary.Type)
poke_df$Primary.Ability <- gsub("\"", "", poke_df$Primary.Ability)
poke_df$Primary.Ability.Description <- gsub("\"", "", poke_df$Primary.Ability.Description)
poke_df$Secondary.Ability <- gsub("\"", "", poke_df$Secondary.Ability)
poke_df$Secondary.Ability.Description <- gsub("\"", "", poke_df$Secondary.Ability.Description)
poke_df$Hidden.Ability <- gsub("\"", "", poke_df$Hidden.Ability)
poke_df$Hidden.Ability.Description <- gsub("\"", "", poke_df$Hidden.Ability.Description)
poke_df$Special.Event.Ability <- gsub("\"", "", poke_df$Special.Event.Ability)
poke_df$Special.Event.Ability.Description <- gsub("\"", "", poke_df$Special.Event.Ability.Description)
poke_df$Game.s..of.Origin <- gsub("\"", "", poke_df$Game.s..of.Origin)
poke_df$Region.of.Origin <- gsub("\"", "", poke_df$Region.of.Origin)

poke_df$Fully.Evolved <- ifelse(poke_df$Pokemon.Name %in% evolved_list, TRUE, FALSE)
head(poke_df, 10)

   ï..Pokemon.Id Pokedex.Number Pokemon.Name Classification
1   1            1              Bulbasaur    Seed Pokemon
2   2            2              Ivysaur      Seed Pokemon
3   3            3              Venusaur     Seed Pokemon
4   4            3              Venusaur     Seed Pokemon
5   5            4              Charmander   Lizard Pokemon
6   6            5              Charmeleon   Flame Pokemon
7   7            6              Charizard    Flame Pokemon
8   8            6              Charizard    Flame Pokemon
9   9            6              Charizard    Flame Pokemon
10 10            7              Squirtle     Tiny Turtle Pokemon
   Alternate.Form.Name Original.Pokemon.ID Legendary.Type Pokemon.Height
1  NULL                NULL                NULL           0.7
2  NULL                NULL                NULL           1.0
3  NULL                NULL                NULL           2.0
4  Mega                3                   NULL           2.4
5  NULL                NULL                NULL           0.6
6  NULL                NULL                NULL           1.1
7  NULL                NULL                NULL           1.7
8  Mega X              7                   NULL           1.7
9  Mega Y              7                   NULL           1.7
10 NULL                NULL                NULL           0.5
   Pokemon.Weight Primary.Type ... Catch.Rate Experience.Growth
1    6.9          Grass        ... 45         Medium Slow
2   13.0          Grass        ... 45         Medium Slow
3  100.0          Grass        ... 45         Medium Slow
4  155.5          Grass        ... 45         Medium Slow
5    8.5          Fire         ... 45         Medium Slow
6   19.0          Fire         ... 45         Medium Slow
7   90.5          Fire         ... 45         Medium Slow
8  110.5          Fire         ... 45         Medium Slow
9  100.5          Fire         ... 45         Medium Slow
10   9.0          Water        ... 45         Medium Slow
   Experience.Growth.Total Experience.Yield Primary.Egg.Group
1  1059860                  64              Monster
2  1059860                 142              Monster
3  1059860                 236              Monster
4  1059860                 281              Monster
5  1059860                  62              Monster
6  1059860                 142              Monster
7  1059860                 240              Monster
8  1059860                 285              Monster
9  1059860                 285              Monster
10 1059860                  63              Monster
   Secondary.Egg.Group Egg.Cycle.Count Pre.Evolution.Pokemon.Id
1  Grass               20              NULL
2  Grass               20              1
3  Grass               20              2
4  Grass               20              NULL
5  Dragon              20              NULL
6  Dragon              20              5
7  Dragon              20              6
8  Dragon              20              NULL
9  Dragon              20              NULL
10 Water 1             20              NULL
   Evolution.Details Fully.Evolved
1  NULL              FALSE
2  Level 16          FALSE
3  Level 32           TRUE
4  NULL               TRUE
5  NULL              FALSE
6  Level 16          FALSE
7  Level 32           TRUE
8  NULL               TRUE
9  NULL               TRUE
10 NULL              FALSE

In [269]:
view_games <- poke_df %>%
    select(Game.s..of.Origin)
head(view_games, 20)

   Game.s..of.Origin
1  Red
2  Red
3  Red
4  X
5  Red
6  Red
7  Red
8  X
9  X
10 Red
11 Red
12 Red
13 X
14 Sword
15 Sword
16 Sword
17 Red
18 Red
19 Diamond
20 Diamond

In [281]:
# now let's add generation for each pokemon
assign_generation <- function(game) {
    if (game == "Red") {
        return(1)
    } else if (game == "Gold") {
        return(2)
    } else if (game == "Ruby") {
        return(3)
    } else if (game == "Fire Red") {
        return(3)
    } else if (game == "Leaf Green") {
        return(3)
    } else if (game == "Emerald") {
        return(3)
    } else if (game == "Diamond") {
        return(4)
    } else if (game == "Platinum") {
        return(4)
    } else if (game == "Black") {
        return(5)
    } else if (game == "Black 2") {
        return(5)
    } else if (game == "X") {
        return(6)
    } else if (game == "Omega Ruby") {
        return(6)
    } else if (game == "Sun") {
        return(7)
    } else if (game == "Ultra Sun") {
        return(7)
    } else if (game == "Let\'s Go Pikachu") {
        return(7)
    } else if (game == "Sword") {
        return(8)
    } else {
        return(NA)
    }
}

In [284]:
# now we add a column based on these
poke_df <- poke_df %>%
    rowwise() %>%
    mutate(Generation = assign_generation(Game.s..of.Origin))

head(poke_df)

  ï..Pokemon.Id Pokedex.Number Pokemon.Name Classification Alternate.Form.Name
1 1             1              Bulbasaur    Seed Pokemon   NULL
2 2             2              Ivysaur      Seed Pokemon   NULL
3 3             3              Venusaur     Seed Pokemon   NULL
4 4             3              Venusaur     Seed Pokemon   Mega
5 5             4              Charmander   Lizard Pokemon NULL
6 6             5              Charmeleon   Flame Pokemon  NULL
  Original.Pokemon.ID Legendary.Type Pokemon.Height Pokemon.Weight Primary.Type
1 NULL                NULL           0.7              6.9          Grass
2 NULL                NULL           1.0             13.0          Grass
3 NULL                NULL           2.0            100.0          Grass
4 3                   NULL           2.4            155.5          Grass
5 NULL                NULL           0.6              8.5          Fire
6 NULL                NULL           1.1             19.0          Fire
  ... Experience.Growth Experience.Growth.Total Experience.Yield
1 ... Medium Slow       1059860                  64
2 ... Medium Slow       1059860                 142
3 ... Medium Slow       1059860                 236
4 ... Medium Slow       1059860                 281
5 ... Medium Slow       1059860                  62
6 ... Medium Slow       1059860                 142
  Primary.Egg.Group Secondary.Egg.Group Egg.Cycle.Count
1 Monster           Grass               20
2 Monster           Grass               20
3 Monster           Grass               20
4 Monster           Grass               20
5 Monster           Dragon              20
6 Monster           Dragon              20
  Pre.Evolution.Pokemon.Id Evolution.Details Fully.Evolved Generation
1 NULL                     NULL              FALSE         1
2 1                        Level 16          FALSE         1
3 2                        Level 32           TRUE         1
4 NULL                     NULL               TRUE         6
5 NULL                     NULL              FALSE         1
6 5                        Level 16          FALSE         1

In [285]:
# seems good, now let's save it so we can work with later
write.csv(poke_df, "C:/Users/kgtrm/Documents/VSC Code/R stuff/PokemonDataCleaned.csv")

In [2]:
poke_df <- read.csv("C:/Users/kgtrm/Documents/VSC Code/R stuff/PokemonDataCleaned.csv")
str(poke_df)
head(poke_df)

'data.frame':	1076 obs. of  50 variables:
 $ X                                : int  1 2 3 4 5 6 7 8 9 10 ...
 $ ï..Pokemon.Id                    : int  1 2 3 4 5 6 7 8 9 10 ...
 $ Pokedex.Number                   : int  1 2 3 3 4 5 6 6 6 7 ...
 $ Pokemon.Name                     : chr  "Bulbasaur" "Ivysaur" "Venusaur" "Venusaur" ...
 $ Classification                   : chr  "Seed Pokemon" "Seed Pokemon" "Seed Pokemon" "Seed Pokemon" ...
 $ Alternate.Form.Name              : chr  "NULL" "NULL" "NULL" "Mega" ...
 $ Original.Pokemon.ID              : chr  "NULL" "NULL" "NULL" "3" ...
 $ Legendary.Type                   : chr  "NULL" "NULL" "NULL" "NULL" ...
 $ Pokemon.Height                   : num  0.7 1 2 2.4 0.6 1.1 1.7 1.7 1.7 0.5 ...
 $ Pokemon.Weight                   : num  6.9 13 100 155.5 8.5 ...
 $ Primary.Type                     : chr  "Grass" "Grass" "Grass" "Grass" ...
 $ Secondary.Type                   : chr  "Poison" "Poison" "Poison" "Poison" ...
 $ Primary.Ability                  : chr  "Overgrow" "Overgrow" "Overgrow" "Thick Fat" ...
 $ Primary.Ability.Description      : chr  "Powers up Grass-type moves when the PokÃ©mon's HP is low." "Powers up Grass-type moves when the PokÃ©mon's HP is low." "Powers up Grass-type moves when the PokÃ©mon's HP is low." "The PokÃ©mon is protected by a layer of thick fat, which halves the damage taken from Fire- and Ice-type moves. " ...
 $ Secondary.Ability                : chr  "NULL" "NULL" "NULL" "NULL" ...
 $ Secondary.Ability.Description    : chr  "NULL" "NULL" "NULL" "NULL" ...
 $ Hidden.Ability                   : chr  "Chlorophyll" "Chlorophyll" "Chlorophyll" "NULL" ...
 $ Hidden.Ability.Description       : chr  "Boosts the PokÃ©mon's Speed stat in harsh sunlight. " "Boosts the PokÃ©mon's Speed stat in harsh sunlight. " "Boosts the PokÃ©mon's Speed stat in harsh sunlight. " "NULL" ...
 $ Special.Event.Ability            : chr  "NULL" "NULL" "NULL" "NULL" ...
 $ Special.Event.Ability.Description: chr  "NULL" "NULL" "NULL" "NULL" ...
 $ Male.Ratio                       : num  87.5 87.5 87.5 87.5 87.5 87.5 87.5 87.5 87.5 87.5 ...
 $ Female.Ratio                     : num  12.5 12.5 12.5 12.5 12.5 12.5 12.5 12.5 12.5 12.5 ...
 $ Base.Happiness                   : int  70 70 70 70 70 70 70 70 70 70 ...
 $ Game.s..of.Origin                : chr  "Red" "Red" "Red" "X" ...
 $ Region.of.Origin                 : chr  "Kanto" "Kanto" "Kanto" "Kalos" ...
 $ Health.Stat                      : int  45 60 80 80 39 58 78 78 78 44 ...
 $ Attack.Stat                      : int  49 62 82 100 52 64 84 130 104 48 ...
 $ Defense.Stat                     : int  49 63 83 123 43 58 78 111 78 65 ...
 $ Special.Attack.Stat              : int  65 80 100 122 60 80 109 130 159 50 ...
 $ Special.Defense.Stat             : int  65 80 100 120 50 65 85 85 115 64 ...
 $ Speed.Stat                       : int  45 60 80 80 65 80 100 100 100 43 ...
 $ Base.Stat.Total                  : int  318 405 525 625 309 405 534 634 634 314 ...
 $ Health.EV                        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Attack.EV                        : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Defense.EV                       : int  0 0 0 0 0 0 0 0 0 1 ...
 $ Special.Attack.EV                : int  1 1 2 2 0 1 3 3 3 0 ...
 $ Special.Defense.EV               : int  0 1 1 1 0 0 0 0 0 0 ...
 $ Speed.EV                         : int  0 0 0 0 1 1 0 0 0 0 ...
 $ EV.Yield.Total                   : int  1 2 3 3 1 2 3 3 3 1 ...
 $ Catch.Rate                       : int  45 45 45 45 45 45 45 45 45 45 ...
 $ Experience.Growth                : chr  "Medium Slow" "Medium Slow" "Medium Slow" "Medium Slow" ...
 $ Experience.Growth.Total          : int  1059860 1059860 1059860 1059860 1059860 1059860 1059860 1059860 1059860 1059860 ...
 $ Experience.Yield                 : int  64 142 236 281 62 142 240 285 285 63 ...
 $ Primary.Egg.Group                : chr  "Monster" "Monster" "Monster" "Monster" ...
 $ Secondary.Egg.Group              : chr  "Grass" "Grass" "Grass" "Grass" ...
 $ Egg.Cycle.Count                  : int  20 20 20 20 20 20 20 20 20 20 ...
 $ Pre.Evolution.Pokemon.Id         : chr  "NULL" "1" "2" "NULL" ...
 $ Evolution.Details                : chr  "NULL" "Level 16" "Level 32" "NULL" ...
 $ Fully.Evolved                    : logi  FALSE FALSE TRUE TRUE FALSE FALSE ...
 $ Generation                       : int  1 1 1 6 1 1 1 6 6 1 ...

  X ï..Pokemon.Id Pokedex.Number Pokemon.Name Classification
1 1 1             1              Bulbasaur    Seed Pokemon
2 2 2             2              Ivysaur      Seed Pokemon
3 3 3             3              Venusaur     Seed Pokemon
4 4 4             3              Venusaur     Seed Pokemon
5 5 5             4              Charmander   Lizard Pokemon
6 6 6             5              Charmeleon   Flame Pokemon
  Alternate.Form.Name Original.Pokemon.ID Legendary.Type Pokemon.Height
1 NULL                NULL                NULL           0.7
2 NULL                NULL                NULL           1.0
3 NULL                NULL                NULL           2.0
4 Mega                3                   NULL           2.4
5 NULL                NULL                NULL           0.6
6 NULL                NULL                NULL           1.1
  Pokemon.Weight ... Experience.Growth Experience.Growth.Total Experience.Yield
1   6.9          ... Medium Slow       1059860                  64
2  13.0          ... Medium Slow       1059860                 142
3 100.0          ... Medium Slow       1059860                 236
4 155.5          ... Medium Slow       1059860                 281
5   8.5          ... Medium Slow       1059860                  62
6  19.0          ... Medium Slow       1059860                 142
  Primary.Egg.Group Secondary.Egg.Group Egg.Cycle.Count
1 Monster           Grass               20
2 Monster           Grass               20
3 Monster           Grass               20
4 Monster           Grass               20
5 Monster           Dragon              20
6 Monster           Dragon              20
  Pre.Evolution.Pokemon.Id Evolution.Details Fully.Evolved Generation
1 NULL                     NULL              FALSE         1
2 1                        Level 16          FALSE         1
3 2                        Level 32           TRUE         1
4 NULL                     NULL               TRUE         6
5 NULL                     NULL              FALSE         1
6 5                        Level 16          FALSE         1